apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-operator
  namespace: opensearch-operator
spec:
  replicas: 1
  strategy:
    type: Recreate # Ensure only one operator pod runs at any given time
  selector:
    matchLabels: { app: opensearch-operator }
  template:
    metadata:
      labels: { app: opensearch-operator }
    spec:
      serviceAccountName: opensearch-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: ghcr.io/reclaim-the-stack/opensearch-operator:0.9.7
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: LOG_LEVEL
              value: debug
